### ISSUE TITLE
Some problems I met when I started to train with mini-dataset

### ISSUE THREAD

**Issue by Apple-father** [weiyithu/SurroundOcc#102]
根据data.md文档我先使用nuscenes-mini数据集运行：
`python generate_occupancy_nuscenes.py --config_path ./config.yaml --label_mapping ./nuscenes.yaml --split [train/val] --save_path [your/save/path] `
生成的npy文件按格式都保存到了./data/nuscenes_occ/samples/下，
然后我进行训练：
./tools/dist_train.sh ./projects/configs/surroundocc/surroundocc.py 1  ./work_dirs/surroundocc
出现了如下的报错：
Traceback (most recent call last):
  File "./tools/train.py", line 261, in <module>
    main()
  File "./tools/train.py", line 257, in main
    meta=meta)
  File "/root/autodl-tmp/SurroundOcc/projects/mmdet3d_plugin/surroundocc/apis/train.py", line 35, in custom_train_model
    meta=meta)
  File "/root/autodl-tmp/SurroundOcc/projects/mmdet3d_plugin/surroundocc/apis/mmdet_train.py", line 201, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 132, in __getitem__
    data = self.prepare_train_data(idx)
  File "/root/autodl-tmp/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 47, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/root/autodl-tmp/SurroundOcc/projects/mmdet3d_plugin/datasets/pipelines/loading.py", line 28, in __call__
    occ = np.load(results['occ_path'])
  File "/root/autodl-tmp/miniconda3/envs/surroundocc/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes_occ/samples/n015-2018-11-21-19-38-26+0800__LIDAR_TOP__1542800382897959.pcd.bin'
我不知道是否需要对occ_path进行手动的更改

**Comment by Rogersljs** [comment]
请问，你解决了吗？

**Comment by Apple-father** [comment]
我已收到

**Comment by peterlyu-HIT** [comment]
您好，我也是一样的问题，找不到这个pcd.bin文件，而我通过python generate_occupancy_nuscenes.py生成的文件都是npy类型的，请问是需要进行格式转换吗，谢谢！

**Comment by Apple-father** [comment]
我已收到

**Comment by Achrefdjaber** [comment]
Please, have you solved it?

**Comment by Rogersljs** [comment]
of course&nbsp;
&nbsp;What problem with your



---Original---
From: ***@***.***&gt;
Date: Thu, May 15, 2025 22:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [weiyithu/SurroundOcc] Some problems I met when I started totrain with mini-dataset (Issue #102)


 Achrefdjaber left a comment (weiyithu/SurroundOcc#102)
 
Please, have you solved it?

**Comment by Achrefdjaber** [comment]
i have the same problem, did you find a solution for this *No such file or directory: './data/nuscenes_occ/samples/n015-2018-11-21-19-38-26+0800__LIDAR_TOP__1542800382897959.pcd.bin'*

**Comment by Rogersljs** [comment]
You can find the dataset processing program and add your file name suffix to the lidar reading part, it is missing



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiyithu/SurroundOcc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月15日(星期四) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiyithu/SurroundOcc] Some problems I met when I started to train with mini-dataset (Issue #102)



 Achrefdjaber left a comment (weiyithu/SurroundOcc#102)
 
i have the same problem, did you find a solution for this No such file or directory: './data/nuscenes_occ/samples/n015-2018-11-21-19-38-26+0800__LIDAR_TOP__1542800382897959.pcd.bin'

**Comment by Apple-father** [comment]
First, you need to generate an .npy file based on the author's code. Second, convert it into a .bin file. When you enter the directory, you will find that all generated files are in .npy format. I reproduced this project a long time ago, and if I remember correctly, this was how the issue was resolved. I hope this helps. What you need to do is to learn how to perform format conversion.

> i have the same problem, did you find a solution for this _No such file or directory: './data/nuscenes_occ/samples/n015-2018-11-21-19-38-26+0800__LIDAR_TOP__1542800382897959.pcd.bin'_

**Comment by Apple-father** [comment]
If you still can't deal with it , rent a server with an RTX 4090 graphics card and large storage space .Download the full-dataset. (Good device is half done.) [doge]
