### ISSUE TITLE
使用40系电脑进行测试似乎会出现不可调和的矛盾

### ISSUE THREAD

**Issue by EveningLin** [weiyithu/SurroundOcc#112]
@weiyithu 想要生成pkl文件，参考 [#40](https://github.com/weiyithu/SurroundOcc/issues/40) 生成pkl，但是发现在cuda11.7，torch113的情况下最低似乎只能下载mmcv-full==1.7.0,则会出现如下报错
`/home/eveing/anaconda3/envs/surroundocc/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/eveing/DL/vision/SurroundOcc/tools/data_converter/create_gt_database.py", line 11, in <module>
    from mmdet3d.core.bbox import box_np_ops as box_np_ops
  File "/home/eveing/anaconda3/envs/surroundocc/lib/python3.7/site-packages/mmdet3d-1.4.0-py3.7.egg/mmdet3d/__init__.py", line 3, in <module>
    import mmdet
  File "/home/eveing/anaconda3/envs/surroundocc/lib/python3.7/site-packages/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.
`请问各位大佬有无成功在40系配置成功的环境要求？或者举一个更具体的例子，使用nusense-mini（即作者没有任何pkl文件和npy文件）如何运行？

**Comment by EveningLin** [comment]
具体地说就是高版本的pytorch能支持chamfer_dist，但是不能兼容mmcv的生成相应文件（应该是pkl，太久了有点忘记了）的要求：mmcv>=1.3.8, <=1.4.0。同时我在a100，cuda11.4的环境上使用作者对应的版本安装chamfer_dist也出现了相应的问题，如下图：
![image](https://github.com/user-attachments/assets/2c8c0a7c-dc08-4bfa-9eb5-a0907a80274c)
但是这已经是mmcv的极限要求
![image](https://github.com/user-attachments/assets/039fb898-f94d-41bc-ac92-e2f14de91e90)
mmcv版本查询https://mmcv.readthedocs.io/zh-cn/1.x/get_started/installation.html

**Comment by 1os3** [comment]
代码层面不兼容40系吧，得改代码。
