### ISSUE TITLE
使用nuscenes-mini数据集时报错

### ISSUE THREAD

**Issue by adreamero** [weiyithu/SurroundOcc#77]
您好，我按照该指令python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data生成了mini数据集的nuscenes_infos_train.pkl和nuscenes_infos_val.pkl，其中文件的目录结构与https://github.com/weiyithu/SurroundOcc/blob/main/docs/data.md描述中的一致，但是我在运行 ./tools/dist_test.sh ./projects/configs/surroundocc/surroundocc.py ./ckpts/surroundocc.pth 1指令时报错，提示找不到相关文件，我只下载了
200x200x16 | val | link | 627M这一个文件，期待您的回复！
Original Traceback (most recent call last):
  File "/ai/AlgCommon/SoftWare/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/ai/AlgCommon/SoftWare/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ai/AlgCommon/SoftWare/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ai/qhchen/AutoLabeling/AnnotationTools/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 129, in __getitem__
    return self.prepare_test_data(idx)
  File "/ai/qhchen/mmdetection3d-0.17.1/mmdet3d/datasets/custom_3d.py", line 172, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/ai/AlgCommon/SoftWare/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/ai/qhchen/AutoLabeling/AnnotationTools/SurroundOcc/projects/mmdet3d_plugin/datasets/pipelines/loading.py", line 27, in __call__
    occ = np.load(results['occ_path'])
  File "/ai/AlgCommon/SoftWare/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes_occ/samples/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin'

**Comment by Apple-father** [comment]
同问这个问题我也在使用mini数据集的时候出现了这个问题，兄弟是怎么解决的 @adreamero
