### ISSUE TITLE
在运行Train SurroundOcc时候发生的报错

### ISSUE THREAD

**Issue by Apple-father** [weiyithu/SurroundOcc#95]
Traceback (most recent call last):
  File "./tools/train.py", line 260, in <module>
    main()
  File "./tools/train.py", line 256, in main
    meta=meta)
  File "/media/xxp/三星固态/for-linux/SurroundOcc/projects/mmdet3d_plugin/surroundocc/apis/train.py", line 35, in custom_train_model
    meta=meta)
  File "/media/xxp/三星固态/for-linux/SurroundOcc/projects/mmdet3d_plugin/surroundocc/apis/mmdet_train.py", line 201, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/xxp/三星固态/for-linux/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 132, in __getitem__
    data = self.prepare_train_data(idx)
  File "/media/xxp/三星固态/for-linux/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 43, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/media/xxp/三星固态/for-linux/SurroundOcc/projects/mmdet3d_plugin/datasets/nuscenes_occupancy_dataset.py", line 72, in get_data_info
    occ_path=info['occ_path'],
KeyError: 'occ_path'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8015) of binary: /home/xxp/anaconda3/envs/Surroundocc/bin/python
Traceback (most recent call last):
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxp/anaconda3/envs/Surroundocc/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-04_23:56:04
  host      : xxp-AI
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8015)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Apple-father** [comment]
我已收到
