### ISSUE TITLE
安装chamfer失败

### ISSUE THREAD

**Issue by Chinartist** [weiyithu/SurroundOcc#97]
`running install
/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'chamfer' extension
creating /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37
Emitting ninja build file /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o.d -pthread -B /data0/wangjingqi/anaconda3/envs/surroundocc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer_cuda.cpp -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2/2] /usr/local/cuda-11.4/bin/nvcc  -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer.cu -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o 
/usr/local/cuda-11.4/bin/nvcc  -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer.cu -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex: In member function ‘bool std::shared_timed_mutex::try_lock_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)’:
/data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex:419:71: error: taking address of temporary [-fpermissive]
  int __ret = pthread_rwlock_timedwrlock(&_M_rwlock, &__ts);
                                                                       ^
/data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex: In member function ‘bool std::shared_timed_mutex::try_lock_shared_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)’:
/data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex:472:67: error: taking address of temporary [-fpermissive]
    __ret = pthread_rwlock_timedrdlock(&_M_rwlock, &__ts);
                                                                   ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
    env=env)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

**Comment by small-zeng** [comment]
> `running install /data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. setuptools.SetuptoolsDeprecationWarning, /data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools. EasyInstallDeprecationWarning, running bdist_egg running egg_info writing chamfer.egg-info/PKG-INFO writing dependency_links to chamfer.egg-info/dependency_links.txt writing top-level names to chamfer.egg-info/top_level.txt reading manifest file 'chamfer.egg-info/SOURCES.txt' writing manifest file 'chamfer.egg-info/SOURCES.txt' installing library code to build/bdist.linux-x86_64/egg running install_lib running build_ext /data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem. warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda)) building 'chamfer' extension creating /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37 Emitting ninja build file /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/build.ninja... Compiling objects... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) [1/2] c++ -MMD -MF /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o.d -pthread -B /data0/wangjingqi/anaconda3/envs/surroundocc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer_cuda.cpp -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [2/2] /usr/local/cuda-11.4/bin/nvcc -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer.cu -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14 FAILED: /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o /usr/local/cuda-11.4/bin/nvcc -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/TH -I/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/data0/wangjingqi/anaconda3/envs/surroundocc/include/python3.7m -c -c /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/chamfer.cu -o /data0/wangjingqi/SurroundOcc/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-37/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14 /data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex: In member function ‘bool std::shared_timed_mutex::try_lock_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)’: /data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex:419:71: error: taking address of temporary [-fpermissive] int __ret = pthread_rwlock_timedwrlock(&_M_rwlock, &__ts); ^ /data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex: In member function ‘bool std::shared_timed_mutex::try_lock_shared_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)’: /data0/wangjingqi/anaconda3/envs/surroundocc/gcc/include/c++/shared_mutex:472:67: error: taking address of temporary [-fpermissive] __ret = pthread_rwlock_timedrdlock(&_M_rwlock, &__ts); ^ ninja: build stopped: subcommand failed. Traceback (most recent call last): File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build env=env) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "setup.py", line 19, in cmdclass={'build_ext': BuildExtension}) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/**init**.py", line 87, in setup return distutils.core.setup(**attrs) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run self.do_egg_install() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install self.run_command('bdist_egg') File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run cmd = self.call_command('install_lib', warn_dir=0) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command self.run_command(cmdname) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run self.build() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build self.run_command('build_ext') File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run _build_ext.run(self) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run self.build_extensions() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions build_ext.build_extensions(self) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions self._build_extensions_serial() File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial self.build_extension(ext) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension _build_ext.build_extension(self, ext) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension depends=ext.depends, File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile with_cuda=with_cuda) File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects error_prefix='Error compiling objects for extension') File "/data0/wangjingqi/anaconda3/envs/surroundocc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension`

I have the same problem, have you solved it?

**Comment by xunian0** [comment]
so how can solve this trouble？i try server days ，but can not find any answer。

**Comment by zzzz-math** [comment]
> so how can solve this trouble？i try server days ，but can not find any answer。

so am i

**Comment by ffengc** [comment]
I also encountered the same problem, how did you solve it in the end? Thank you

**Comment by wanzghen0123** [comment]
作者提供的gcc指定版本过老，编译过程中存在各种冲突和依赖问题。重新建立一个新环境（一定要重新建立conda，在原来环境上升级gcc没有用），安装gcc7以上的版本，可以安装通过。例如：conda install -c conda-forge gcc_linux-64=8
